PREFIX=Brighter_Than_Today-
FILES_TO_LIST=lyrics.txt chord-chart.html chord-sheet.cho chord-sheet.pdf

gen/${PREFIX}lyrics.txt: lyrics.txt
	cp lyrics.txt gen/${PREFIX}lyrics.txt

include ../Makefile.common
